name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a993b373343f40c0e3ffb0f3f09dceeb5d297b3d1057cde58c216304fadf88e8"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
