name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "392aafb34beb01337af94b726e877105733dcc99aa3a243bb53d9944faa6d4df"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
