name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99a9feae3949bd1209dc471f3e3a1012f1a49a443c538d2023bfa72b7754a703"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
