name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb9ef6622e1d3db30d5f79bd5916a2c1a752659ea2cde01985098d94e84a49c4"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
