name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dcce811e2056c7b21a21d421f8dbe229e42c1feab3b3463ed6272caa61b308f"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
