name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "462c7e3b46e4aaac7c183101d97b1cb0597b5dbdf03cf86ccff31039f6a23be0"

[versions]
forge = "47.4.11"
minecraft = "1.20.1"
