name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1e00e077def8430fcdce9779e32e36fd4ed45653410683b5f0bcbbb13c00951"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
