name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4612c0685fa19e893a6dc82b7ea9058e8e30e22f24a334636a884096bcbc41d"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
