name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b624fbe0ea7a5b8e8880408a1f1bb12357d9ca9357dcb868927d7ad94a92631b"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
