name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42ba8085061749644b76a7c4b8427c3120fb449413312a12b832987ba97522a3"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
