name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7e944748d5a0f89d72d5cb2e7362b9335bf1b91c1ff93416b0fadf86f707c8c"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
