name = "Leentech Neo"
author = "Tim & Leen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0834f24594c5d2a240f646322ebbe4fc286cfa9ab410fa4401385bbdd9682fd6"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
