#spawn Categories(MONSTER, CREATURE, ... defaults..., custom pools from other mods
spawnCategories = ["MONSTER,70", "CREATURE,30", "AMBIENT,10", "AXOLOTLS,5", "UNDERGROUND_WATER_CREATURE,10", "WATER_CREATURE,15", "WATER_AMBIENT,30"]

