#Shows hullback building and damage progress. Turning this off solve incompatibility issues with shaders but will sacrifice some visual flair
hullbackArmorProgress = true
#Determines how far hullback sounds travel.
#Range: 0.0 ~ 5.0
hullbackSoundDistance = 2.0

